<?php
/**
 * Created by PhpStorm.
 * User: Stevennight
 * Date: 2018/4/26
 * Time: 17:29
 */

namespace stevennight\menu_breadcrumbs;

use dmstr\widgets\Menu;
use yii\helpers\Html;

class MenuBreadcrumbs extends Menu
{
    public $parentActiveIfItemHidden = true;        //子项隐藏后是否激活父项。
    public $breadcrumbs = [];

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        var_dump(array_reverse($this->breadcrumbs));
    }


    protected function normalizeItems($items, &$active)
    {
        foreach ($items as $i => $item) {
            if (!$this->parentActiveIfItemHidden && isset($item['visible']) && !$item['visible']) {
                unset($items[$i]);
                continue;
            }
            if (!isset($item['label'])) {
                $item['label'] = '';
            }
            $encodeLabel = isset($item['encode']) ? $item['encode'] : $this->encodeLabels;
            $items[$i]['label'] = $encodeLabel ? Html::encode($item['label']) : $item['label'];
            $items[$i]['icon'] = isset($item['icon']) ? $item['icon'] : '';
            $hasActiveChild = false;
            if (isset($item['items'])) {
                $items[$i]['items'] = $this->normalizeItems($item['items'], $hasActiveChild);
                if (empty($items[$i]['items']) && $this->hideEmptyItems) {
                    unset($items[$i]['items']);
                    if (!isset($item['url'])) {
                        unset($items[$i]);
                        continue;
                    }
                }
            }
            if (!isset($item['active'])) {
                if ($this->activateParents && $hasActiveChild || $this->activateItems && $this->isItemActive($item)) {
                    $active = $items[$i]['active'] = true;
                    //设置breadcrumbs
                    $breadcrumb = [
                        'label' => $item['label'],
                        'url' => $item['url'],
                    ];
                    $this->breadcrumbs[] = $breadcrumb;
                } else {
                    $items[$i]['active'] = false;
                }
            } elseif ($item['active']) {
                $active = true;
            }
            //visible设置为不显示，因此unset掉。(激活父级，最前面的将不激活父级。)
            if(isset($item['visible']) && !$item['visible']){
                unset($items[$i]);
                continue;
            }
        }
        return array_values($items);
    }

}